JCR-4536 optionally allow insecure TLS connections (self-signed cert,
apache/jackrabbit pull request #92
Opened 2020-07-03 19:12 UTC by kwin

invalid common name)

2020-07-03 19:13 UTC, kwin commented
This replaces #88. @reschke  Please tell me what you think?

2020-07-03 19:32 UTC, kwin commented on jackrabbit-spi2dav/src/main/java/org/apache/jackrabbit/spi2dav/RepositoryServiceImpl.java
> +        // TODO: move to ConnectionOptions as well
I tend to move this option as well!

2020-07-06 11:21 UTC, kwin commented on jackrabbit-spi2dav/src/main/java/org/apache/jackrabbit/spi2dav/RepositoryServiceImpl.java
> +        // TODO: move to ConnectionOptions as well
Done in https://github.com/apache/jackrabbit/pull/92/commits/9ef98400bcf513aa3ce1fedabad95a032a3d543e

2020-07-09 07:40 UTC, kwin commented
I tested the changes with https://github.com/apache/jackrabbit-filevault/pull/92/files and it works fine there.

2020-07-16 13:26 UTC, kwin commented on jackrabbit-spi2dav/src/main/java/org/apache/jackrabbit/spi2dav/Spi2davRepositoryServiceFactory.java
> +        return new RepositoryServiceImpl(uri, idFactory, nameFactory, pathFactory, vFactory, itemInfoCacheSize, ConnectionOptions.fromServiceFactoryParameters("org.apache.jackrabbit.spi2dav", paramet
no dynamic prefix should be used for connection parameters

2020-07-16 13:44 UTC, reschke reviewed
Looks good overall.

2020-07-16 13:44 UTC, reschke commented on jackrabbit-spi2dav/src/main/java/org/apache/jackrabbit/spi2dav/ConnectionOptions.java
> +     */
we should be able to use {@link ...} here

2020-07-16 13:44 UTC, reschke commented on jackrabbit-spi2dav/src/main/java/org/apache/jackrabbit/spi2dav/ConnectionOptions.java
> +                    // using default
maybe log the exception?

(also whitespace)

2020-07-16 13:44 UTC, reschke commented on jackrabbit-spi2dav/src/main/java/org/apache/jackrabbit/spi2dav/RepositoryServiceImpl.java
> +    @Deprecated
I believe we can just remove this.

2020-07-17 06:31 UTC, reschke requested changes

2020-07-17 06:31 UTC, reschke commented on jackrabbit-spi2dav/pom.xml
> +    </dependencies>
Could you please backout the whitespace changes?

2020-07-17 08:21 UTC, kwin commented
Merged in https://github.com/apache/jackrabbit/commit/d545fa178cccf42f60cbc9d28121c7f0a99db3b1.

2020-07-17 08:21 UTC, closed without merging